export const SKINS_DATA = [
  {
    id: 'classic',
    name: 'Classic Emerald Dino',
    rarity: 'COMMON',
    rarityClass: 'badge-common',
    rarityBorder: 'rarity-common',
    price_coins: 0,
    price_diamonds: 0,
    isFree: true,
    emoji: '🦖',
    color: '#10b981',
    accentColor: '#059669',
    description: 'The original adventurer. Emerald gradient body with red headband.',
    perk: 'Balanced baseline physics',
    perkIcon: '⚖️',
    highlights: ['Emerald gradient body', 'Red headband with ribbon', 'White tooth', 'Classic sneakers']
  },
  {
    id: 'cyberpunk',
    name: 'Cyber Neon Visor',
    rarity: 'RARE',
    rarityClass: 'badge-rare',
    rarityBorder: 'rarity-rare',
    price_coins: 150,
    price_diamonds: 0,
    isFree: false,
    emoji: '🥽',
    color: '#38bdf8',
    accentColor: '#0ea5e9',
    description: 'Obsidian scales with electric cyan visor and laser scanline animation.',
    perk: '+5% Distance score multiplier',
    perkIcon: '⚡',
    highlights: ['Obsidian dark scales', 'Animated cyan visor', 'Laser scanline', 'Neon violet back fins']
  },
  {
    id: 'singlish',
    name: 'Singlish Hawker Champ',
    rarity: 'EPIC',
    rarityClass: 'badge-epic',
    rarityBorder: 'rarity-epic',
    price_coins: 300,
    price_diamonds: 0,
    isFree: false,
    emoji: '🦁',
    color: '#8b5cf6',
    accentColor: '#7c3aed',
    description: 'Crimson-green body with Merlion emblem and CHAMP headband.',
    perk: '+10% Gold coins magnet',
    perkIcon: '🧲',
    highlights: ['Merlion 🦁 chest emblem', 'Crimson-green body', 'Golden dorsal spikes', 'CHAMP headband']
  },
  {
    id: 'saigon',
    name: 'Saigon Street Racer',
    rarity: 'EPIC',
    rarityClass: 'badge-epic',
    rarityBorder: 'rarity-epic',
    price_coins: 450,
    price_diamonds: 0,
    isFree: false,
    emoji: '🏎️',
    color: '#f97316',
    accentColor: '#ea580c',
    description: 'Traditional Nón Lá conical hat tilted stylishly with fiery orange sneakers.',
    perk: 'Lower air drag & softer jump',
    perkIcon: '🌬️',
    highlights: ['Vietnamese Nón Lá 🎋', 'Fiery orange sneakers', 'Speed flame trails', 'Agile build']
  },
  {
    id: 'cosmic',
    name: 'Cosmic Nebula Dino',
    rarity: 'LEGENDARY',
    rarityClass: 'badge-legendary',
    rarityBorder: 'rarity-legendary',
    price_coins: 800,
    price_diamonds: 0,
    isFree: false,
    emoji: '🌌',
    color: '#a855f7',
    accentColor: '#9333ea',
    description: 'Deep violet galaxy body with twinkling stellar flecks and stardust particle trail.',
    perk: 'Stardust trail on every landing',
    perkIcon: '✨',
    highlights: ['Galaxy violet body', 'Twinkling star flecks', 'Stardust particle trail', 'Cosmic crown']
  },
  {
    id: 'golden',
    name: 'Golden King Dino',
    rarity: 'LEGENDARY',
    rarityClass: 'badge-legendary',
    rarityBorder: 'rarity-legendary',
    price_coins: 1200,
    price_diamonds: 5,
    isFree: false,
    emoji: '👑',
    color: '#fbbf24',
    accentColor: '#f59e0b',
    description: '24K radiant gold metallic finish with Imperial Crown & Ruby gemstone.',
    perk: '+20% All quiz rewards',
    perkIcon: '💰',
    highlights: ['24K pure gold finish', 'Royal Imperial Crown', 'Ruby gemstone', 'Diamond studded armor']
  }
];
